version: '3.8'

services:
  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    ports:
      - "3000:3000"
    networks:
      test-net:
        aliases:
          - juice-shop-service

  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: integration-tests
    depends_on:
      juice-shop:
        condition: service_started
    networks:
      - test-net
    entrypoint: ["sh", "-c", "sleep 60"]

  zap-proxy:
    build:
      context: .
      dockerfile: Dockerfile-ZAP
    container_name: ZAP
    networks:
      test-net:
        aliases:
          - zap-service

networks:
  test-net:
    driver: bridge
