version: '3.8'

services:
  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    ports:
      - "3000:3000"
    networks:
      test-net:
        aliases:
          - juice-shop-service
    healthcheck:
      test: [ "CMD-SHELL", "curl -f -X GET http://localhost:3000/rest/products/search?q= || exit 1" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: integration-tests
    depends_on:
      juice-shop:
        condition: service_healthy
    networks:
      - test-net

  zap-proxy:
    build:
      context: .
      dockerfile: Dockerfile-ZAP
    container_name: ZAP
    networks:
      test-net:
        aliases:
          - zap-service

networks:
  test-net:
    driver: bridge