version: '3'
services:
  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    ports:
      - "3000:3000"
    networks:
      test-net:
        aliases:
          - juice-shop-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: integration-tests
    depends_on:
      juice-shop:
        condition: service_healthy
    networks:
      - test-net
    volumes:
      - ./allure-results-from-network:/usr/src/app/target
    environment:
      - TEST_URL=http://juice-shop-service:3000

networks:
  test-net:
    driver: bridge
