# Use the bkimminich/juice-shop image as the base image
FROM bkimminich/juice-shop

# Install curl
#RUN apt-get update && \
#    apt-get install -y curl && \
#    rm -rf /var/lib/apt/lists/*

# Expose the port that Juice Shop runs on
EXPOSE 3000

# Start the Juice Shop application
CMD ["npm", "start"]
