version: '3.8'

services:
  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    ports:
      - "3000:3000"
    networks:
      test-net:
        ipv4_address: 172.18.0.2

  #integration-tests:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile-Integration-Test
  #  container_name: integration-tests
  #  networks:
  #    test-net:
  #      ipv4_address: 172.18.0.3
  #  deploy:
  #    resources:
  #      limits:
  #        memory: 2g  # Set memory limit to 2GB

  zap-proxy:
    build:
      context: .
      dockerfile: Dockerfile-ZAP
    container_name: ZAP
    ports:
      - "9090:9090"
    networks:
      test-net:
        ipv4_address: 172.18.0.4

networks:
  test-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
