version: '3.8'

services:
  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    ports:
      - "3000:3000"
    networks:
      test-net:
        ipv4_address: 172.18.0.2
        aliases:
          - juice-shop-service
    healthcheck:
      test: [ "CMD-SHELL", "curl -f -X GET http://localhost:3000/rest/products/search?q= || exit 1" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: integration-tests
    depends_on:
      juice-shop:
        condition: service_healthy
    networks:
      test-net:
        ipv4_address: 172.18.0.3


networks:
  test-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
