name: Run Docker Compose

on:
  workflow_dispatch:

jobs:
  run-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: docker compose build

      - name: Run Docker Compose in detached mode
        run: docker compose up -d

      - name: Wait for services to start
        run: sleep 30

      - name: Retrieve and display integration test logs
        run: docker logs integration-tests

      - name: Copy DAST Report from Docker container
        run: docker cp integration-tests:/app/DAST-report ./
        continue-on-error: true

      - name: Upload DAST report artifact
        uses: actions/upload-artifact@v3
        with:
          name: dast-report
          path: ./DAST-report/dast-report.html

      - name: Shutdown Docker Compose
        run: docker compose down
