name: Run Docker Compose

on:
  workflow_dispatch:

jobs:
  run-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Run Juice-shop on port 3000
        run: docker run -p 3000:3000 bkimminich/juice-shop

      - name: Check if Juice Shop is up and running
        run: |
          for i in {1..10}; do
            curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/rest/products/search?q=
            if [ $? -eq 0 ]; then
              echo "Juice Shop is up and running."
              break
            fi
            echo "Waiting for Juice Shop to start..."
            sleep 10
          done