name: Run Test with Allure-Report

on:
  workflow_dispatch:

jobs:
  run-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Docker Compose in detached mode
        run: docker compose up -d

      - name: Wait for services to start
        run: sleep 30

      - name: Build the integration test image
        run: docker build -f Dockerfile-Integration-Test -t my-integration-test-image .

      - name: Run integration-tests container
        run: docker run --name integration-tests --network juice-shop-test_test-net my-integration-test-image

      - name: Retrieve and display test logs
        run: docker logs integration-tests

      - name: Copy Allure Report from Docker container
        run: docker cp integration-tests:/app/target/site/allure-report ./allure-report
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
