name: Run Test with Allure-Report

on:
  workflow_dispatch:

jobs:
  run-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Docker Compose in detached mode
        run: docker compose up -d

      - name: Wait for services to start
        run: sleep 30

      - name: Build the integration test image
        run: docker build -f Dockerfile-Integration-Test -t my-integration-test-image .

      - name: Run integration-tests container
        run: docker run --name integration-tests --network juice-shop-test_test-net my-integration-test-image

      - name: Retrieve and display test logs
        run: docker logs integration-tests

      - name: Copy Allure Report from Docker container
        run: docker cp integration-tests:/app/target/site/allure-report ./allure-report
        continue-on-error: true

      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: ./allure-report

      - name: Copy DAST Report from Docker container
        run: docker cp integration-tests:/app/DAST-report ./
        continue-on-error: true

      - name: Upload DAST report artifact
        uses: actions/upload-artifact@v3
        with:
          name: dast-report
          path: ./DAST-report/dast-report.html

      - name: Shutdown Docker Compose
        run: docker compose down

      - name: Deploy Allure Report to GitHub Pages
        if: success() # Deploy only if the previous steps succeeded
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # Clone the `gh-pages` branch
          git clone --branch gh-pages https://github.com/${{ github.repository }} gh-pages

          # Copy the Allure report into the `gh-pages` directory
          rsync -av --delete ./allure-report/ gh-pages/

          # Commit and push the changes to the `gh-pages` branch
          cd gh-pages
          git add .
          git commit -m "Update Allure report"
          git push origin gh-pages
