name: Run Docker Compose

on:
  workflow_dispatch:

jobs:
  run-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Docker Compose in detached mode
        run: docker compose up -d

      - name: Run Integration Tests
        run: docker exec integration-tests mvn clean install site -DenvConfig=default -DsuiteFile=juiceShop-testsuit.xml -DremoteExecution=false -Dmaven.wagon.http.pool=false -Dhttp.keepAlive=false allure:report

      - name: Retrieve and display test logs
        run: docker logs integration-tests

      - name: Copy Allure Report from Docker container
        run: docker cp integration-tests:/app/target/site/allure-report ./allure-report
        continue-on-error: true

      - name: Shutdown Docker Compose
        run: docker compose down
