version: '3.8'

services:
  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    ports:
      - "3000:3000"
    networks:
      test-net:
        ipv4_address: 172.18.0.2

  zap-proxy:
    build:
      context: .
      dockerfile: Dockerfile-ZAP
    container_name: ZAP
    ports:
      - "9090:9090"
    networks:
      test-net:
        ipv4_address: 172.18.0.4

  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile-Integration-Test
    depends_on:
      - juice-shop
      - zap-proxy
    networks:
      test-net:
    environment:
      - TEST_ENV_VAR=value

networks:
  test-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
